### ISSUE TITLE
Cắt html từ layout có sẵn

### ISSUE THREAD

**Issue by AnhDuyNAD** [AnhDuyNAD/lms_admin_web#2]
**Yêu cầu**
Dựa vào layout đã chọn cắt html/css để render lên.

**Kết quả cần**
Loại bỏ bớt 1 số layout, loại bỏ hiệu ứng js, chỉ lấy html css.

**Tiến độ**
Xong screen nào thì up lên liền để code tính năng cho screen đó.

**Các trang cần làm**
1 - Homepage -> 4h

.... Đang viết tiếp

**Comment by nhtnguyen119** [comment]
deo lam nua

**Comment by nhtnguyen119** [comment]
lam trong 10 nam
